development:
  adapter: postgresql
  encoding: unicode
  database: zoo
  pool: 5
  host: localhost
  username: postgres
  password: umasenha

test:
  adapter: postgresql
  encoding: unicode
  database: zoo
  pool: 5
  host: localhost
  username: postgres
  password: umasenha